import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
import { User } from 'src/modules/user/entities/user.entity';
import { Customer } from 'src/modules/customer/entities/customer.entity';
import { CustomerContactPerson } from '../../customer/entities/customer-contact-person.entity';

export enum ProductProcurementRequestStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  OFFER_CREATED = 'OFFER_CREATED', //auto generated by app
  OFFER_SENT_TO_CUSTOMER = 'OFFER_SENT_TO_CUSTOMER', //auto generated by app
  OFFER_ACCEPTED = 'OFFER_ACCEPTED', //auto generated by app
  OFFER_CANCELED = 'OFFER_CANCELED', //auto generated by app
  CANCELED = 'CANCELED', // manually set by user (can be set only if previous status is IN_PROGRESS
}

@Entity({ name: 'product_procurement_requests' })
export class ProductProcurementRequest {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  status: string;

  @Column()
  category: string; // can be a separate table in the future, same table as one from product entity

  @Column({ name: 'generation_method' })
  generationMethod: string; // website/email/telefonic/intalnire/licitatie

  @Column({ name: 'receiving_method' })
  receivingMethod: string; // initiata de client/initiata de romtek/initiata de furnizor(i)/targ-expozitie

  @Column({ name: 'project_name' })
  projectName: string;

  @Column({ name: 'project_code', nullable: true })
  projectCode: string;

  @Column({ nullable: true })
  description: string;

  @Column({ name: 'response_deadline_date', type: 'date' })
  responseDeadlineDate: Date;

  @Column({ nullable: true })
  rfq: string;

  @Column({ name: 'assigned_user_id' })
  assignedUserId: number;

  @ManyToOne(() => User, (user) => user.id)
  @JoinColumn({ name: 'assigned_user_id' })
  readonly assignedUser?: Readonly<User>;

  @Column({ name: 'customer_id' })
  customerId: number;

  @ManyToOne(() => Customer, (customer) => customer.id)
  @JoinColumn({ name: 'customer_id' })
  readonly customer?: Readonly<Customer>;

  @Column({ name: 'customer_contact_person_id' })
  customerContactPersonId: number;

  @ManyToOne(() => CustomerContactPerson, (person) => person.id)
  @JoinColumn({ name: 'customer_contact_person_id' })
  readonly customerContactPerson?: Readonly<CustomerContactPerson>;

  @Column({ name: 'cc_customer_contact_person_id' })
  ccCustomerContactPersonId: number;

  @ManyToOne(() => CustomerContactPerson, (person) => person.id)
  @JoinColumn({ name: 'cc_customer_contact_person_id' })
  readonly ccCustomerContactPerson?: Readonly<CustomerContactPerson>;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;
}
